# Generated by Django 5.2.7 on 2026-10-05 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Số phòng')),
                ('kind', models.CharField(max_length=80, verbose_name='Hạng phòng')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Số khách')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá mỗi đêm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='positive_price'), models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='positive_capacity')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Tên khách')),
                ('phone', models.CharField(max_length=20, verbose_name='Điện thoại')),
                ('check_in', models.DateField(verbose_name='Nhận phòng')),
                ('check_out', models.DateField(verbose_name='Trả phòng')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Số khách')),
                ('total', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy')], default='confirmed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.room')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='valid_dates'), models.CheckConstraint(condition=models.Q(('guests__gt', 0)), name='positive_guests')],
            },
        ),
    ]
