#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname hotel --set=owner="$OWNER_PASSWORD" --set=app="$APP_PASSWORD" --set=monitor="$MONITOR_PASSWORD" <<'SQL'
CREATE ROLE hotel_owner LOGIN PASSWORD :'owner' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE hotel_app LOGIN PASSWORD :'app' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE hotel_monitor LOGIN PASSWORD :'monitor' NOSUPERUSER NOCREATEDB NOCREATEROLE;
ALTER DATABASE hotel OWNER TO hotel_owner;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO hotel_owner;
GRANT USAGE ON SCHEMA public TO hotel_app;
ALTER DEFAULT PRIVILEGES FOR ROLE hotel_owner IN SCHEMA public GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO hotel_app;
ALTER DEFAULT PRIVILEGES FOR ROLE hotel_owner IN SCHEMA public GRANT USAGE,SELECT ON SEQUENCES TO hotel_app;
GRANT pg_monitor TO hotel_monitor;
SQL
